# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5465907c955ea6628b37ae57a6b50cd5bb328d9f928e102789e99f2267626b770444904cf856da7be6d409fd0219acaa884358f84d0dbc40536e732891c507d7

test:
  secret_key_base: f0edb2174c184557a1d860abfb6d5841c5cb0656321a451e6f5755f7b36deedc58fa145a4ff170554d100b0604025afdea1b95da0c2b8eddce2fd53022315350

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
