# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4e09fd7ec401c0e83ad17f01f97e5a256c65b626c83dd38861364e5a6e668095b5a91fcb69cb4e67de6193435bac16ef89a1e0496266069ed1722c9dbe9aa3e

test:
  secret_key_base: 9c931d7d6a9f2c4c886309ce4e4b2cb568614571f232aed5f40ffef48c5e3dde1907d21d2a86fd557d069f0ff3fbfcd0b37dd23b1051fe54968f8e1bc0f0225d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
